Fix unused-result warning
This fixes the following warning emitted by clang++ under -Og:

interpreter_test.cc:114:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]

Test: presubmit
Bug: 294796809
Change-Id: Ie1ef5affc7cf946e4962e6e9a6cf96b486fcabd7